### ISSUE TITLE
Histo (2D Image) Notebook Completion

### ISSUE THREAD

**Issue by olhawloch** [gmachiraju/K2#1]
Is it possible to have (or do you plan on adding), an example from start to end for the use of Prospector Heads with images? I would love to see how the whole pipeline works for a ViT or CLIP model for tumor localization in pathology slides.

**Comment by gmachiraju** [comment]
Hi there! Sorry for the large delay in response. This repo is coming back online after a change in our contributors' work statuses. Hope to be more active in the coming months!

To answer your question: this repo doesn't contain embedding scripts for pathology or proteins (which contained a lot of custom functions), but we do show scripts and notebooks for language. However, in a previous repo [()](https://github.com/gmachiraju/lofi) that mirrored a preceding workshop paper, you can see examples of embedding pathology slide patches. Check out the file at: `src/Cam-Step1-Embed.ipynb` for ideas!
